// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :many
WITH created_feed_follow AS (
	INSERT INTO feed_follows  (user_id, feed_id, created_at, updated_at) 
	VALUES(
		$1,
		$2,
		$3,
		$4
	)
	RETURNING id, created_at, updated_at, user_id, feed_id
) SELECT feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_follows.feed_id, users.id, users.created_at, users.updated_at, users.name, feeds.feed_id, feeds.name, url, feeds.user_id, last_fetched_at 
FROM feed_follows 
INNER JOIN users on users.id = feed_follows.user_id
INNER JOIN feeds on feed_follows.feed_id = feeds.feed_id
`

type CreateFeedFollowParams struct {
	UserID    uuid.UUID
	FeedID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateFeedFollowRow struct {
	ID            int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
	FeedID        int32
	ID_2          uuid.UUID
	CreatedAt_2   time.Time
	UpdatedAt_2   time.Time
	Name          string
	FeedID_2      int32
	Name_2        string
	Url           string
	UserID_2      uuid.UUID
	LastFetchedAt sql.NullTime
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) ([]CreateFeedFollowRow, error) {
	rows, err := q.db.QueryContext(ctx, createFeedFollow,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateFeedFollowRow
	for rows.Next() {
		var i CreateFeedFollowRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.Name,
			&i.FeedID_2,
			&i.Name_2,
			&i.Url,
			&i.UserID_2,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFollow = `-- name: DeleteFollow :one
DELETE FROM feed_follows
WHERE $1 = feed_follows.user_id and $2 = feed_follows.feed_id
RETURNING id, created_at, updated_at, user_id, feed_id
`

type DeleteFollowParams struct {
	UserID uuid.UUID
	FeedID int32
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, deleteFollow, arg.UserID, arg.FeedID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const getFeedFollowsByUser = `-- name: GetFeedFollowsByUser :many
SELECT feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_follows.feed_id, users.id, users.created_at, users.updated_at, users.name, feeds.feed_id, feeds.name, url, feeds.user_id, last_fetched_at
FROM feed_follows
INNER JOIN users on users.id = feed_follows.user_id
INNER JOIN feeds on feed_follows.feed_id = feeds.feed_id
WHERE users.ID = $1
`

type GetFeedFollowsByUserRow struct {
	ID            int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UserID        uuid.UUID
	FeedID        int32
	ID_2          uuid.UUID
	CreatedAt_2   time.Time
	UpdatedAt_2   time.Time
	Name          string
	FeedID_2      int32
	Name_2        string
	Url           string
	UserID_2      uuid.UUID
	LastFetchedAt sql.NullTime
}

func (q *Queries) GetFeedFollowsByUser(ctx context.Context, id uuid.UUID) ([]GetFeedFollowsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsByUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsByUserRow
	for rows.Next() {
		var i GetFeedFollowsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.Name,
			&i.FeedID_2,
			&i.Name_2,
			&i.Url,
			&i.UserID_2,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
